In [6]:
import numpy as np
import pandas as pd
import scipy.io as sio
import matplotlib.pyplot as plt

#1.Crear una matriz de Numpy aleatoria de 3 dimensiones y un size de 11520000
a=np.random.rand(288,160,250)#Filas,Columnas,Profundidad
#filas=288, columnas=160, profundidad=250

#2.Crea una copia de la matriz creada en el ítem anterior
b = a.copy()

#3.Muestra todos los atributos propios de dicha matriz , dimensión, tamaño, etc..
print(f"Forma: {a.shape}")
print(f"Tamaño: {a.size}")
print(f"Numero de Dimensiones: {a.ndim}")

#4.Modificar su forma y pasarla a 2D
a = a.reshape(288,160*250)#filas, columnas*profundidad
#filas=288, columnas=160*250
print("\nMatriz 2D: ")
print(f"Forma: {a.shape}")
print(f"Tamaño: {a.size}")
print(f"Numero de Dimensiones: {a.ndim}")

#5.Crea una función que reciba la matriz anterior y la pase a un objeto tipo dataframe de Pandas
def aDataFrame(a):
    return pd.DataFrame(a)
# print(aDataFrame(a))
frame=aDataFrame(a)


#6.Crear una función que permita cargar un archivo .mat y .csv
def cargarArchivo(archivo):
    if archivo.endswith(".mat"):
        return sio.loadmat(archivo)
    elif archivo.endswith(".csv"):
        return pd.read_csv(archivo)
    
#7.Crear funciones de suma, resta, multiplicación, división, promedio, desviación estándar
#NOTA: Estas funciones deben permitir hacer estos procesos a lo largo de un eje (usando Numpy) ¿Cómo se implementaría usando Pandas?
def suma(a,axis=0):
    return np.sum(a,axis=axis)

def resta(a,axis=0):
    return np.diff(a,axis=axis)

def multiplicacion(a,axis=0):
    return np.prod(a,axis=axis)

def division(a,axis=0):
    return np.divide(a[:-1], a[1:], axis=axis)

def promedio(a,axis=0):
    return np.mean(a,axis=axis)

def desviacionEstandar(a,axis=0):
    return np.std(a,axis=axis)


#8.Crear una función que permita graficar un histograma de los datos de la matriz anterior
# Función para graficar señales
def graficar_senal(signal, title="", xlabel="", ylabel="", legend=False, grid=False):
    plt.plot(signal)
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    if legend:
        plt.legend()
    if grid:
        plt.grid()
    plt.show()

# Función para graficar histogramas
def graficar_histograma(signal, title="", xlabel="", ylabel="", legend=False, grid=False):
    plt.hist(signal, bins='auto')
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    if legend:
        plt.legend()
    if grid:
        plt.grid()
    plt.show()

# Función para graficar stems
def graficar_stem(signal, title="", xlabel="", ylabel="", legend=False, grid=False):
    plt.stem(signal)
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    if legend:
        plt.legend()
    if grid:
        plt.grid()
    plt.show()

# Función para graficar gráficos de barras
def graficar_barras(signal, title="", xlabel="", ylabel="", legend=False, grid=False):
    x = np.arange(len(signal))
    plt.bar(x, signal)
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    if legend:
        plt.legend()
    if grid:
        plt.grid()
    plt.show()

# Función para graficar gráficos de pastel
def graficar_pastel(signal, title="", labels=[], legend=False, grid=False):
    plt.pie(signal, labels=labels)
    plt.title(title)
    if legend:
        plt.legend()
    if grid:
        plt.grid()
    plt.show()

# graficar_senal(a[0], title="Señal", xlabel="Tiempo", ylabel="Amplitud", legend=False, grid=True)
# graficar_histograma(a[0], title="Histograma", xlabel="Amplitud", ylabel="Frecuencia", legend=False, grid=True)  
# graficar_stem(a[0], title="Stem", xlabel="Tiempo", ylabel="Amplitud", legend=False, grid=True)
# graficar_barras(a[0], title="Barras", xlabel="Tiempo", ylabel="Amplitud", legend=False, grid=True)
# graficar_pastel(a[0], title="Pastel", labels=["A","B","C","D","E"], legend=False, grid=True)

#9. Para la graficación permitir al usuario elegir entre un diseño de dos subplots (vertical u horizontal)
layout = 'horizontal' # 'vertical' o 'horizontal'
if layout == 'vertical':
    fig = plt.figure()
    ax1 = fig.add_subplot(2, 1, 1)
    ax2 = fig.add_subplot(2, 1, 2)
elif layout == 'horizontal':
    fig = plt.figure()
    ax1 = fig.add_subplot(1, 2, 1)
    ax2 = fig.add_subplot(1, 2, 2)

# Graficar datos en subplot 1
ax1.plot(a[0], a[1])
ax1.set_title("Título del subplot 1")
ax1.set_xlabel("Eje x")
ax1.set_ylabel("Eje y")
ax1.legend()
ax1.grid()

# Graficar datos en subplot 2
ax2.hist(a[2], bins=10)
ax2.set_title("Título del subplot 2")
ax2.set_xlabel("Eje x")
ax2.set_ylabel("Eje y")
ax2.legend()
ax2.grid()

# Mostrar figura
plt.show()



No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.


Forma: (288, 160, 250)
Tamaño: 11520000
Numero de Dimensiones: 3
[[0.68632425 0.48898091 0.24367978 ... 0.29582818 0.50645125 0.33573687]
 [0.91848601 0.58976932 0.37592429 ... 0.56791135 0.12147161 0.91831911]
 [0.67200607 0.44485584 0.37061643 ... 0.77737029 0.19235434 0.91912171]
 ...
 [0.96609786 0.73770168 0.07433005 ... 0.68823587 0.38175498 0.63545584]
 [0.14514825 0.00106008 0.97639907 ... 0.79585643 0.75237234 0.96190614]
 [0.20134323 0.62946686 0.65170107 ... 0.00332514 0.95860631 0.36343608]]

Matriz 2D: 
Forma: (288, 40000)
Tamaño: 11520000
Numero de Dimensiones: 2


En Matplotlib, legend activa o desactiva la leyenda del gráfico, la cual muestra información sobre las diferentes series o elementos representados en el gráfico. Si el valor es True, la leyenda se activa.

Por otro lado, grid activa o desactiva la cuadrícula en el gráfico. Si el valor es True, la cuadrícula se activa. La cuadrícula es una serie de líneas horizontales y verticales que pueden ayudar a visualizar mejor los datos.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

class DataAnalysis:
    def __init__(self, data):
        self.data = data
    
    def reshape_data(self, new_shape):
        self.data = self.data.reshape(new_shape)
    
    def convert_to_dataframe(self, columns):
        self.data = pd.DataFrame(self.data, columns=columns)
    
    def plot_signal(self, title="", xlabel="", ylabel="", legend=True, grid=True):
        plt.plot(self.data)
        plt.title(title)
        plt.xlabel(xlabel)
        plt.ylabel(ylabel)
        if legend:
            plt.legend()
        if grid:
            plt.grid()
    
    def plot_histogram(self, title="", xlabel="", ylabel="", bins=10, legend=True, grid=True):
        plt.hist(self.data, bins=bins)
        plt.title(title)
        plt.xlabel(xlabel)
        plt.ylabel(ylabel)
        if legend:
            plt.legend()
        if grid:
            plt.grid()
    
    def plot_stem(self, title="", xlabel="", ylabel="", legend=True, grid=True):
        plt.stem(self.data)
        plt.title(title)
        plt.xlabel(xlabel)
        plt.ylabel(ylabel)
        if legend:
            plt.legend()
        if grid:
            plt.grid()
    
    def plot_bar(self, title="", xlabel="", ylabel="", legend=True, grid=True):
        plt.bar(range(len(self.data)), self.data)
        plt.title(title)
        plt.xlabel(xlabel)
        plt.ylabel(ylabel)
        if legend:
            plt.legend()
        if grid:
            plt.grid()
    
    def plot_pie(self, title="", legend=True, grid=True):
        plt.pie(self.data, labels=self.data.index)
        plt.title(title)
        if legend:
            plt.legend()
        if grid:
            plt.grid()


In [ ]:
# Crear objeto DataAnalysis
data_analysis = DataAnalysis(np.random.rand(100))

# Cambiar forma a 2D
data_analysis.reshape_data((25, 4))

# Convertir a DataFrame de Pandas
data_analysis.convert_to_dataframe(['Columna 1', 'Columna 2', 'Columna 3', 'Columna 4'])

# Graficar señal
data_analysis.plot_signal(title='Gráfico de señal', xlabel='Tiempo (s)', ylabel='Amplitud')

# Graficar histograma
data_analysis.plot_histogram(title='Histograma de datos', xlabel='Valor', ylabel='Frecuencia')


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

class MyDataAnalyzer:
    def __init__(self, data):
        self.data = data
        plt.ion()
        
    def to_dataframe(self):
        df = pd.DataFrame(self.data)
        return df
        
    def sum(self, axis=0):
        return np.sum(self.data, axis=axis)
        
    def subtract(self, axis=0):
        return np.subtract(self.data, np.mean(self.data, axis=axis))
        
    def multiply(self, axis=0):
        return np.prod(self.data, axis=axis)
        
    def divide(self, axis=0):
        return np.divide(self.data, np.std(self.data, axis=axis))
        
    def average(self, axis=0):
        return np.mean(self.data, axis=axis)
        
    def std_deviation(self, axis=0):
        return np.std(self.data, axis=axis)
        
    def plot_signal(self, title="", x_label="", y_label="", legend=False, grid=False):
        plt.figure()
        plt.title(title)
        plt.xlabel(x_label)
        plt.ylabel(y_label)
        plt.plot(self.data)
        
        if legend:
            plt.legend()
            
        if grid:
            plt.grid()
            
        plt.show()
        
    def plot_histogram(self, title="", x_label="", y_label="", legend=False, grid=False):
        plt.figure()
        plt.title(title)
        plt.xlabel(x_label)
        plt.ylabel(y_label)
        plt.hist(self.data)
        
        if legend:
            plt.legend()
            
        if grid:
            plt.grid()
            
        plt.show()
        
    def plot_stem(self, title="", x_label="", y_label="", legend=False, grid=False):
        plt.figure()
        plt.title(title)
        plt.xlabel(x_label)
        plt.ylabel(y_label)
        plt.stem(self.data)
        
        if legend:
            plt.legend()
            
        if grid:
            plt.grid()
            
        plt.show()
        
    def plot_bar(self, title="", x_label="", y_label="", legend=False, grid=False):
        plt.figure()
        plt.title(title)
        plt.xlabel(x_label)
        plt.ylabel(y_label)
        plt.bar(range(len(self.data)), self.data)
        
        if legend:
            plt.legend()
            
        if grid:
            plt.grid()
            
        plt.show()
        
    def plot_pie(self, title="", legend=False, grid=False):
        plt.figure()
        plt.title(title)
        plt.pie(self.data)
        
        if legend:
            plt.legend()
            
        if grid:
            plt.grid()
            
        plt.show()

def main():
    # Example usage
    data = np.random.rand(288, 160, 250)
    analyzer = MyDataAnalyzer(data.reshape(288, 160*250))
    df = analyzer.to_dataframe()
    s = analyzer.sum(axis=0)
    sub = analyzer.subtract(axis=1)
    mul = analyzer.multiply(axis=2)
    div = analyzer.divide(axis=0)
    avg = analyzer.average(axis=1)
    std = analyzer.std_deviation(axis=2)


# Otros

In [1]:
import numpy as np

shape = (120, 160, 600)
rand_array = np.random.rand(*shape)

In [2]:
print(f"Forma: {rand_array.shape}")
print(f"Tamaño: {rand_array.size}")
print(f"Numero de Dimensiones: {rand_array.ndim}")

Forma: (120, 160, 600)
Tamaño: 11520000
Numero de Dimensiones: 3


In [3]:
flat_array = rand_array.reshape((11520000, 1))
flat_array

array([[0.11580601],
       [0.08687178],
       [0.36996346],
       ...,
       [0.44975457],
       [0.49470253],
       [0.49666905]])

In [4]:
#Numpy
import numpy as np

def numpy_sum(arr, axis=0):
    return np.sum(arr, axis=axis)

def numpy_diff(arr, axis=0):
    return np.diff(arr, axis=axis)

def numpy_multiply(arr, axis=0):
    return np.prod(arr, axis=axis)

def numpy_divide(arr, axis=0):
    return np.divide(arr[:-1], arr[1:], axis=axis)

def numpy_mean(arr, axis=0):
    return np.mean(arr, axis=axis)

def numpy_std(arr, axis=0):
    return np.std(arr, axis=axis)


In [ ]:
#Pandaas
import pandas as pd

def pandas_sum(df, axis=0):
    return df.sum(axis=axis)

def pandas_diff(df, axis=0):
    return df.diff(axis=axis)

def pandas_multiply(df, axis=0):
    return df.prod(axis=axis)

def pandas_divide(df, axis=0):
    return df[:-1].div(df[1:], axis=axis)

def pandas_mean(df, axis=0):
    return df.mean(axis=axis)

def pandas_std(df, axis=0):
    return df.std(axis=axis)


# Version 3

In [ ]:
import numpy as np

matriz = np.random.rand(60, 160, 12000)  # 60x160x12000 = 11520000

matriz_copia = matriz.copy()

print(f"Dimensiones: {matriz.ndim}")
print(f"Forma: {matriz.shape}")
print(f"Tipo de datos: {matriz.dtype}")
print(f"Tamaño: {matriz.size}")
print(f"Memoria utilizada: {matriz.nbytes} bytes")

matriz_2d = matriz.reshape(matriz.shape[0] * matriz.shape[1], matriz.shape[2])

import pandas as pd

def matriz_a_dataframe(matriz):
    df = pd.DataFrame(matriz)
    return df


from scipy.io import loadmat

def cargar_matriz(matriz_file):
    matriz = loadmat(matriz_file)
    return matriz

def cargar_csv(matriz_file):
    matriz = pd.read_csv(matriz_file)
    return matriz

def suma(matriz, eje):
    return np.sum(matriz, axis=eje)

def resta(matriz1, matriz2):
    return np.subtract(matriz1, matriz2)

def multiplicacion(matriz1, matriz2):
    return np.multiply(matriz1, matriz2)

def division(matriz1, matriz2):
    return np.divide(matriz1, matriz2)

def promedio(matriz, eje):
    return np.mean(matriz, axis=eje)

def desviacion_estandar(matriz, eje):
    return np.std(matriz, axis=eje)

#8. Usar matplotlib para graficar la señal anterior y crear funciones para graficar histogramas, stems, barras, pies.
import matplotlib.pyplot as plt

def graficar_senal(senal, titulo="", xlabel="", ylabel="", leyenda=False, cuadricula=False):
    plt.figure()
    plt.plot(senal)
    plt.title(titulo)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    if leyenda:
        plt.legend()
    if cuadricula:
        plt.grid()
    plt.show()

def graficar_histograma(datos, titulo="", xlabel="", ylabel="", leyenda=False, cuadricula=False):
    plt.figure()
    plt.hist(datos)
    plt.title(titulo)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    if leyenda:
        plt.legend()
    if cuadricula:
        plt.grid()
    plt.show()

def graficar_stem(senal, titulo="", xlabel="", ylabel="", leyenda=False, cuadricula=False):
    plt.figure()
    plt.stem(senal)
    plt.title(titulo)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    if leyenda:
        plt.legend()
    if cuadricula:
        plt.grid()
    plt.show()

def graficar_barras(datos, titulo="", xlabel="", ylabel="", leyenda=False, cuadricula=False):
    plt.figure()
    plt.bar(range(len(datos)), datos)
    plt.title(titulo)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    if leyenda:
        plt.legend()
    if cuadricula:
        plt.grid()
    plt.show()

def graficar_pie(datos, titulo="", leyenda=False, cuadricula=False):
    plt.figure()
    plt.pie(datos)
    plt.title(titulo)
    if leyenda:
        plt.legend()
    if cuadricula:
        plt.grid()
    plt.show()


#9. ¡Por supuesto! Continuamos con la solución:

Usar matplotlib para graficar la señal anterior y crear funciones para graficar histogramas, stems, barras, pies.
python
Copy code
import matplotlib.pyplot as plt

def graficar_senal(senal, titulo="", xlabel="", ylabel="", leyenda=False, cuadricula=False):
    plt.figure()
    plt.plot(senal)
    plt.title(titulo)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    if leyenda:
        plt.legend()
    if cuadricula:
        plt.grid()
    plt.show()

def graficar_histograma(datos, titulo="", xlabel="", ylabel="", leyenda=False, cuadricula=False):
    plt.figure()
    plt.hist(datos)
    plt.title(titulo)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    if leyenda:
        plt.legend()
    if cuadricula:
        plt.grid()
    plt.show()

def graficar_stem(senal, titulo="", xlabel="", ylabel="", leyenda=False, cuadricula=False):
    plt.figure()
    plt.stem(senal)
    plt.title(titulo)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    if leyenda:
        plt.legend()
    if cuadricula:
        plt.grid()
    plt.show()

def graficar_barras(datos, titulo="", xlabel="", ylabel="", leyenda=False, cuadricula=False):
    plt.figure()
    plt.bar(range(len(datos)), datos)
    plt.title(titulo)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    if leyenda:
        plt.legend()
    if cuadricula:
        plt.grid()
    plt.show()

def graficar_pie(datos, titulo="", leyenda=False, cuadricula=False):
    plt.figure()
    plt.pie(datos)
    plt.title(titulo)
    if leyenda:
        plt.legend()
    if cuadricula:
        plt.grid()
    plt.show()

# 10. Para la graficación permitir al usuario elegir entre un diseño de dos subplots (vertical u horizontal).
def graficar_subplots(senales, titulo="", xlabel="", ylabel="", leyenda=False, cuadricula=False, orientacion='vertical'):
    fig, ax = plt.subplots(nrows=len(senales), ncols=1, sharex=True, sharey=True)
    if orientacion == 'vertical':
        for i in range(len(senales)):
            ax[i].plot(senales[i])
            ax[i].set_title(titulo)
            ax[i].set_xlabel(xlabel)
            ax[i].set_ylabel(ylabel)
            if leyenda:
                ax[i].legend()
            if cuadricula:
                ax[i].grid()
    elif orientacion == 'horizontal':
        for i in range(len(senales)):
            ax[i].plot(senales[i])
            ax[i].set_title(titulo)
            ax[i].set_xlabel(xlabel)
            ax[i].set_ylabel(ylabel)
            if leyenda:
                ax[i].legend()
            if cuadricula:
                ax[i].grid()
        plt.subplots_adjust(hspace=0.5)
    plt.show()


#11. Crear una clase que integre las funciones
import numpy as np
import pandas as pd
import scipy.io as sio

class HerramientasAnalisisSenales:
    
    def __init__(self, senal):
        self.senal = senal
    
    def copiar_senal(self):
        self.copia_senal = self.senal.copy()
    
    def mostrar_atributos(self):
        print("Dimensiones:", self.senal.ndim)
        print("Forma:", self.senal.shape)
        print("Tamaño:", self.senal.size)
        print("Tipo de datos:", self.senal.dtype)
    
    def modificar_forma(self, nueva_forma):
        self.senal = self.senal.reshape(nueva_forma)
    
    def convertir_a_dataframe(self):
        self.senal = pd.DataFrame(self.senal)
    
    def cargar_archivo(self, ruta_archivo):
        if ruta_archivo.endswith(".mat"):
            self.senal = sio.loadmat(ruta_archivo)
        elif ruta_archivo.endswith(".csv"):
            self.senal = pd.read_csv(ruta_archivo)
    
    def suma(self, eje=None):
        return np.sum(self.senal, axis=eje)
    
    def resta(self, eje=None):
        return np.subtract(self.senal, axis=eje)
    
    def multiplicacion(self, eje=None):
        return np.multiply(self.senal, axis=eje)
    
    def division(self, eje=None):
        return np.divide(self.senal, axis=eje)
    
    def promedio(self, eje=None):
        return np.mean(self.senal, axis=eje)
    
    def desviacion_estandar(self, eje=None):
        return np.std(self.senal, axis=eje)
    
    def graficar_senal(self, titulo="", xlabel="", ylabel="", leyenda=False, cuadricula=False):
        plt.figure()
        plt.plot(self.senal)
        plt.title(titulo)
        plt.xlabel(xlabel)
        plt.ylabel(ylabel)
        if leyenda:
            plt.legend()
        if cuadricula:
            plt.grid()
        plt.show()

    def graficar_histograma(self, titulo="", xlabel="", ylabel="", leyenda=False, cuadricula=False):
        plt.figure()
        plt.hist(self.senal)
        plt.title(titulo)
        plt.xlabel(xlabel)
        plt.ylabel(ylabel)
        if leyenda:
            plt.legend()
        if cuadricula:
            plt.grid()
        plt.show()

    def graficar_stem(self, titulo="", xlabel="", ylabel="", leyenda=False, cuadricula=False):
        plt.figure()
        plt.stem(self.senal)
        plt.title(titulo)
        plt.xlabel(xlabel)
        plt.ylabel(ylabel)
        if leyenda:
            plt.legend()
        if cuadricula:
            plt.grid()
        plt.show()

    def graficar_barras(self, titulo="", xlabel="", ylabel="", leyenda=False, cuadricula=False):
        plt.figure()
        plt.bar(range(len(self.senal)), self.senal)
        plt.title(titulo)
        plt.xlabel(xlabel)
        plt.ylabel(ylabel)
        if leyenda:
            plt.legend()
        if cuadricula:
            plt.grid()
        plt.show()

    def graficar_pie(self, titulo="", leyenda=False, cuadricula=False):
        plt.figure()
        plt.pie(self.senal)
        plt.title(titulo)
        if leyenda:
            plt.legend()
        if cuadricula:
            plt.grid()
        plt.show()

    def graficar_subplots(self, titulo="", xlabel="", ylabel="", leyenda=False, cuadricula=False, orientacion='vertical'):
        fig, ax = plt.subplots(nrows=len(self.senal), ncols=1, sharex=True, sharey=True)
        if orientacion == 'vertical':
            for i in range(len(self.senal)):
                ax[i].plot(self.senal[i])
                ax[i].set_title(titulo)
                ax[i].set_xlabel(xlabel)
                ax[i].set_ylabel(ylabel)
                if leyenda:
                    ax[i].legend()
                if cuadricula:
                    ax[i].grid()
        elif orientacion == 'horizontal':
            for i in range(len(self.senal)):
                ax[i].plot(self.senal[i])
                ax[i].set_title(titulo)
                ax[i].set_xlabel(xlabel)
                ax[i].set_ylabel(ylabel)
                if leyenda:
                    ax[i].legend()
                if cuadricula:
                    ax[i].grid()
            plt.subplots_adjust(hspace=0.5)
        plt.show()
    
    import matplotlib.pyplot as plt

    def plot_signal(signal):
        title = input("Ingrese el título del gráfico: ")
        xlabel = input("Ingrese la etiqueta del eje X: ")
        ylabel = input("Ingrese la etiqueta del eje Y: ")
        plt.plot(signal)
        plt.title(title)
        plt.xlabel(xlabel)
        plt.ylabel(ylabel)
        plt.grid(True)
        plt.show()

    def plot_histogram(signal):
        title = input("Ingrese el título del gráfico: ")
        xlabel = input("Ingrese la etiqueta del eje X: ")
        ylabel = input("Ingrese la etiqueta del eje Y: ")
   
import matplotlib.pyplot as plt
plt.ion()

signal = Signal.from_mat('signal.mat')
signal.plot(title='Señal', xlabel='Tiempo
